# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

matrix:
  include:
    - r: devel
    - r: release
    - r: oldrel
    - r: 3.3
    - r: 3.2
