// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_sdmx_
List read_sdmx_(std::string path, bool is_file);
RcppExport SEXP _readsdmx_read_sdmx_(SEXP pathSEXP, SEXP is_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type is_file(is_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(read_sdmx_(path, is_file));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readsdmx_read_sdmx_", (DL_FUNC) &_readsdmx_read_sdmx_, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_readsdmx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
