# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_sdmx_ <- function(fname) {
    .Call(`_readsdmx_read_sdmx_`, fname)
}

read_sdmx_connection_ <- function(bdata) {
    .Call(`_readsdmx_read_sdmx_connection_`, bdata)
}

